### ISSUE TITLE
Blissfest rebranding to BlissRI

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.blissri.com#1]
## Summary

In an abundance of caution, the Blissfest organization has opted to rebrand the event as BlissRI to avoid any potential copyright / trademark issues with any existing events operating in the same space.

## Details

The details of this will include:
1. [x] Forking the repo from _www.blissfestri.com_ -> _www.blissri.com_
1. [x] Transfer all pre-existing projects / labels / milestones / etc
1. [x] Setup Netlify + deploy previews + GitHub actions
1. [x] Update website content / branding / socials / logos - https://github.com/AnalogStudiosRI/www.blissri.com/pull/5
1. [x] Setup DNS to point to Netlify and verify propagation
    <details>
      <img src="https://github.com/AnalogStudiosRI/www.blissri.com/assets/895923/055dd2d3-12e8-4523-8ed3-03e346c97846"/>
      <img src="https://github.com/AnalogStudiosRI/www.blissri.com/assets/895923/35fc7eb0-b4e1-4da0-9341-c3480d985ad4"/>
    </details>
1. [x] ⚠️ Setup redirects from the old domain to the new domain - https://github.com/AnalogStudiosRI/www.blissfestri.com/pull/139
1. [x] Backup / Cancel Setup Analytics
1. [x] Update website backlinks / profiles
    - Facebook
    - Instagram
1. [x] Setup 2023 archive sub domain under blissri.com
1. [x] Transfer all pre-existing issues - https://github.com/AnalogStudiosRI/www.blissri.com/issues/1#issuecomment-2077691146
1. [x] Transfer all WIP PRs / branches
1. [x] Archive the old repository

## Odds and Ends (fast follows)
1. [x] Archive page DNS not working? - https://github.com/AnalogStudiosRI/www.blissri.com/issues/1#issuecomment-2077663143
1. [x] cURL not showing new `Location` header (but browser works?) - splitting off to https://github.com/AnalogStudiosRI/www.blissri.com/issues/20
    - https://github.com/AnalogStudiosRI/www.blissri.com/issues/1#issuecomment-2077587603
1. [x] Change default branch? - documented it for now - https://github.com/AnalogStudiosRI/www.blissri.com/commit/5c036d412de52b3e454c2272a30f506a61e04f09
    - https://github.com/orgs/community/discussions/11729
    - https://github.com/AnalogStudiosRI/www.blissri.com/issues/1#issuecomment-2077727827

**Comment by thescientist13** [comment]
DNS is still propagating, but it just popped up over HTTP 👀 
<img width="1717" alt="Screen Shot 2024-04-23 at 8 26 46 PM" src="https://github.com/AnalogStudiosRI/www.blissri.com/assets/895923/4b6e73cc-0c1e-477e-89b2-fda81ee38bd7">

**Comment by thescientist13** [comment]
So did the archive, and the app specific build URL looks good
https://archive-2023--luxury-biscotti-4dd724.netlify.app

But DNS doesn't seem to be working, not sure if that also takes 24 hours
https://2023.blissri.com/

----

Not sure if it's related to files already being built?
![Screen Shot 2024-04-25 at 12 11 10 PM](https://github.com/AnalogStudiosRI/www.blissri.com/assets/895923/7dcb6aac-5c62-4449-9524-1ba2f02baff9)

**Comment by thescientist13** [comment]
A lot of the pre-existing issues are related to design aesthetics missed in the first launch, and since we plan a more robust rebrand for next year, I think these can be categorized as "good enough" for this year as well
- https://github.com/AnalogStudiosRI/www.blissfestri.com/issues/109
- https://github.com/AnalogStudiosRI/www.blissfestri.com/issues/104
- https://github.com/AnalogStudiosRI/www.blissfestri.com/issues/82
- https://github.com/AnalogStudiosRI/www.blissfestri.com/issues/78
- https://github.com/AnalogStudiosRI/www.blissfestri.com/issues/44
- https://github.com/AnalogStudiosRI/www.blissfestri.com/issues/43

**Comment by thescientist13** [comment]
So at least with the old repo archived, it will at least prevent PRs from going through all the way, but the default is still the fork 🤷‍♂️ 
![Screen Shot 2024-04-25 at 12 41 31 PM](https://github.com/AnalogStudiosRI/www.blissri.com/assets/895923/a18ea345-40f9-4e58-b600-3022a755c73f)
